/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Repository.HoaDonRepository;
import Service.HoaDonServies;
import entity.HoaDonViewModel;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FPTSHOP
 */
public class HoaDon extends javax.swing.JFrame {
  DefaultTableModel defaultTableModel;
    private  HoaDonRepository donRepository;
    public HoaDon() {
        initComponents();
        donRepository = new HoaDonRepository();
        loadDataToTable();
    }
 

    private void loadDataToTable() {
       List<Model.HoaDon> listHoaDon = donRepository.GetAllHD();
    DefaultTableModel model = (DefaultTableModel) tbl_hoadon.getModel();
    model.setRowCount(0); // Xóa các hàng hiện tại

    // Khởi tạo DecimalFormat để định dạng tiền tệ
    DecimalFormat currencyFormat = new DecimalFormat("#,###");

    for (Model.HoaDon hd : listHoaDon) {
        model.addRow(new Object[]{
            hd.getMa(),  // Mã hóa đơn
            hd.getKhachHang() != null ? hd.getKhachHang().getTen() : "Chưa có thông tin", // Tên khách hàng (kiểm tra null)
            currencyFormat.format(hd.getTongTien()),  // Tổng tiền định dạng
            hd.getNgayTao(),  // Ngày tạo
            hd.getNgayThanhToan(),  // Ngày thanh toán
            hd.getTinhTrang() == 0 ? "Chưa thanh toán" : "Đã thanh toán", // Trạng thái
            hd.getGhichu() != null ? hd.getGhichu() : "Không có" // Ghi chú (kiểm tra null)
        });
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_hoadon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "Tên KH", "Tổng Tiền", "Ngày Tạo", "Ngày Thanh Toán", "Trạng Thái", "Ghi Chú"
            }
        ));
        jScrollPane1.setViewportView(tbl_hoadon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_hoadon;
    // End of variables declaration//GEN-END:variables
}
