/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Model.KhachHang;
import Repository.KhachHangRepository;
import Repositorys.ImplKhachHangRepository;
import Service.DanhSachKHServices;
import Service.HoaDonServies;
import Services.ImplDSKHService;
import Services.ImplHoaDonService;
import entity.DanhSachKHViewModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FPTSHOP
 */
public class KhachHang2 extends javax.swing.JFrame {

     SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
 DefaultTableModel defaultTableModel = new DefaultTableModel();
 private ImplKhachHangRepository repository;
 List<DanhSachKHViewModel> listLS;
    List<KhachHang> list;
    ImplDSKHService KH;
    ImplKhachHangRepository KHRP;
    String Ma;
     ImplHoaDonService hoaDonServiec;
    public KhachHang2(String MaHD) {
        initComponents();
         repository = new KhachHangRepository();
          KH = new DanhSachKHServices();
        KHRP = new KhachHangRepository();
        hoaDonServiec = new HoaDonServies();
        list = KHRP.getall();
        Ma = MaHD;
        showtable(list);
    }
 public void showtable(List<KhachHang> list){
      defaultTableModel = (DefaultTableModel) tb_khachHang.getModel();
        defaultTableModel.setRowCount(0);
        for (KhachHang khachHang : list) {
            defaultTableModel.addRow(khachHang.toDataRow());
        }

}
  public int layid() {
        Integer row = tb_khachHang.getSelectedRow();
        int id = (int) tb_khachHang.getValueAt(row, 0);
        return id;

    }
   private KhachHang getData() {
        KhachHang cv = new KhachHang();
        cv.setTen(txt_ten.getText());
        cv.setTendem(txt_tendem.getText());
        cv.setHo(txt_ho.getText());
        int gt;
        if (rdo_nam.isSelected()) {
            gt = 0;
        } else {
            gt = 1;
        }
        cv.setGioitinh(gt);
        cv.setNgaysinh(date_ngaysinh.getDate());
        cv.setSdt(txt_sdt.getText());
        cv.setEmail(txt_email.getText());

        return cv;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_khachHang = new javax.swing.JTable();
        rdo_nu = new javax.swing.JRadioButton();
        rdo_nam = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txt_timKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        txt_tendem = new javax.swing.JTextField();
        txt_ho = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date_ngaysinh = new com.toedter.calendar.JDateChooser();
        txt_sdt = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_chon = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_maKH = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tb_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ma KH", "Họ Tên Khách Hàng", "Giới Tính", "Ngày Sinh", "SĐT", "Email"
            }
        ));
        tb_khachHang.setGridColor(new java.awt.Color(255, 255, 255));
        tb_khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_khachHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_khachHang);

        buttonGroup1.add(rdo_nu);
        rdo_nu.setText("Nữ");

        buttonGroup1.add(rdo_nam);
        rdo_nam.setSelected(true);
        rdo_nam.setText("Nam");
        rdo_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_namActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Giới tính");

        txt_timKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_timKiemCaretUpdate(evt);
            }
        });
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });
        txt_timKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timKiemKeyReleased(evt);
            }
        });

        jLabel1.setText("Tên");

        jLabel2.setText("Tên đệm");

        jLabel3.setText("Họ");

        jLabel4.setText("Ngày Sinh");

        jLabel5.setText("SĐT");

        jLabel6.setText("Email");

        date_ngaysinh.setDateFormatString("yyyy-MM-dd");

        btn_chon.setText("Chọn");
        btn_chon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã KH");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        jLabel9.setText("Tìm Kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdo_nam)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_ten)
                                        .addComponent(txt_tendem)
                                        .addComponent(txt_ho, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_sdt)
                            .addComponent(txt_email)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_chon)
                                .addGap(18, 18, 18)
                                .addComponent(btn_them)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_maKH)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(rdo_nu)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(date_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tendem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_maKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdo_nam)
                    .addComponent(rdo_nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_chon)
                    .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_khachHangMouseClicked
        int id = layid();
        int row =tb_khachHang.getSelectedRow();
        KhachHang kh = list.get(row);

        txt_ten.setText(kh.getTen());
        txt_tendem.setText(kh.getTendem());
        txt_ho.setText(kh.getHo());
    String gt = tb_khachHang.getValueAt(row, 3).toString();
if ("Nam".equals(gt)) {
    rdo_nam.setSelected(true);
} else if ("Nữ".equals(gt)) {
    rdo_nu.setSelected(true);
}
        date_ngaysinh.setDate((Date) tb_khachHang.getValueAt(row, 4));
        txt_sdt.setText(kh.getSdt());
        txt_email.setText(kh.getEmail());
        txt_maKH.setText(kh.getMa());
    }//GEN-LAST:event_tb_khachHangMouseClicked

    private void txt_timKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_timKiemCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemCaretUpdate

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    private void txt_timKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timKiemKeyReleased
defaultTableModel = (DefaultTableModel) tb_khachHang.getModel();
        defaultTableModel.setRowCount(0);

        String searchText = txt_timKiem.getText().toLowerCase();
        for (Model.KhachHang kh : list) {
            if (kh.getMa().toLowerCase().contains(searchText) ||
                kh.getHo().toLowerCase().contains(searchText) ||
                kh.getTendem().toLowerCase().contains(searchText) ||
                kh.getTen().toLowerCase().contains(searchText) ||
                kh.getSdt().contains(searchText) ||
                kh.getEmail().toLowerCase().contains(searchText)) {

                Object[] rowData = new Object[7];
                rowData[0] = kh.getId();
                rowData[1] = kh.getMa();
                rowData[2] = kh.getHo() + " " + kh.getTendem() + " " + kh.getTen();
                rowData[3] = kh.getGioitinh()==0?"Nam":"Nữ";
                rowData[4] = (kh.getNgaysinh());
                rowData[5] = kh.getSdt();
                rowData[6] = kh.getEmail();

                defaultTableModel.addRow(rowData);
            }
        } 
    }//GEN-LAST:event_txt_timKiemKeyReleased

    private void btn_chonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonActionPerformed
      int rowKh = tb_khachHang.getSelectedRow();
        if (rowKh < 0) {
            JOptionPane.showMessageDialog(this, "lựa 1 khách hàng");
            return;
        }
        Integer updateHoaDonKh = hoaDonServiec.updateHoaDonKhachHang(Integer.parseInt(tb_khachHang.getValueAt(rowKh, 0).toString()), Ma);
        dispose();
    }//GEN-LAST:event_btn_chonActionPerformed

    private void rdo_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo_namActionPerformed
 private boolean validateKhachHang() {
    String sdtPattern = "(0\\d{9})"; // Biểu thức chính quy cho số điện thoại
    Pattern pattern = Pattern.compile("^[0-9]+$"); // Biểu thức chính quy cho kiểm tra số

    // Kiểm tra thông tin khách hàng
    if (txt_ten.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên khách hàng!");
        return false;
    }

    if (pattern.matcher(txt_ten.getText()).find()) {
        JOptionPane.showMessageDialog(this, "Tên khách hàng không được nhập số!");
        return false;
    }

    if (txt_ten.getText().length() > 30) {
        JOptionPane.showMessageDialog(this, "Tên khách hàng không được quá 30 kí tự!");
        return false;
    }

    if (txt_sdt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập số điện thoại!");
        return false;
    }
    
    if (txt_maKH.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Bạn chưa nhập Ma!");
        return false;
    }


    try {
        if (!txt_sdt.getText().matches(sdtPattern)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng!");
            return false;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi kiểm tra số điện thoại: " + e.getMessage());
        return false;
    }

    // Nếu không có lỗi xảy ra trong quá trình kiểm tra
    return true;
} private Model.KhachHang getFrom(){
   Model.KhachHang kh = new Model.KhachHang();
   kh.setMa(txt_maKH.getText());
   kh.setHo(txt_ho.getText());
   kh.setTendem(txt_tendem.getText());
   kh.setTen(txt_ten.getText());
   Date ngaysinh = date_ngaysinh.getDate();
         kh.setSdt(txt_sdt.getText());
        kh.setEmail(txt_email.getText());
        
        if (ngaysinh!=null) {
          kh.setNgaysinh(ngaysinh);   
         }
        
        int gt;
        if (rdo_nam.isSelected()) {
            gt = 0;
        } else {
            gt = 1;
        }
        return kh;
    }
    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
     if (validateKhachHang()) {
            Model.KhachHang kh = getFrom();
            if (repository.add(kh) != null) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                list = KHRP.getall();
                showtable(list);
             
            } else {
                JOptionPane.showMessageDialog(this, "Không thêm được");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Thông tin khách hàng không hợp lệ");
        }
    }//GEN-LAST:event_btn_themActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KhachHang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KhachHang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KhachHang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KhachHang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KhachHang2(tbl_HoaDon.getValueAt(rowHD, 0).toString()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chon;
    private javax.swing.JButton btn_them;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser date_ngaysinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable tb_khachHang;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_ho;
    private javax.swing.JTextField txt_maKH;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_tendem;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
