
package poly.edu.component;

import Model.Model_Menu;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import poly.edu.event.EventMenuSelected;


/**
 *
 * @author Yen Nhi
 */
public class Menu extends javax.swing.JPanel {

    private EventMenuSelected event;
    
    public void addEventMenuSelected(EventMenuSelected event) {
        this.event = event;
        listMenu1.addEventMenuSelected(event);
    }
    
    public Menu() {
        initComponents();
        setOpaque(false);
        listMenu1.setOpaque(false);
        init();
    }
    
    private void init() {
        listMenu1.addItem(new Model_Menu("", "DANH MỤC", Model_Menu.MenuType.TITLE));
        listMenu1.addItem(new Model_Menu("1", "TRANG CHỦ", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("2", "SẢN PHẨM", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("3", "VOUCHER", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("4", "BÁN HÀNG", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("8", "ĐỢT GIẢM GIÁ", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("5", "KHÁCH HÀNG", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("7", "HÓA ĐƠN", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("6", "NHÂN VIÊN", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("10", "ĐĂNG XUẤT", Model_Menu.MenuType.MENU));
        listMenu1.addItem(new Model_Menu("", "", Model_Menu.MenuType.EMPTY));
    }

    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
    
    // Thay đổi màu gradient theo yêu cầu của bạn
    GradientPaint g = new GradientPaint(0, 0, Color.decode("#FF7E5F"), 0, getHeight(), Color.decode("#FEB47B"));
    g2.setPaint(g);
    
    // Thay đổi bo tròn và vị trí của các hình chữ nhật
    int cornerRadius = 20; // Độ bo tròn các góc
    int rectWidth = getWidth() - 20;
    int rectHeight = getHeight() - 20;
    
    // Vẽ hình chữ nhật bo tròn
    g2.fillRoundRect(10, 10, rectWidth, rectHeight, cornerRadius, cornerRadius);
    
    // Vẽ hình chữ nhật thường ở cạnh phải
    g2.fillRect(getWidth() - 10, 10, 10, rectHeight);
    
    super.paintChildren(grphcs);
    }
    
    private int x;
    private int y;
    
    public void initMoving(JFrame frame) {
           panelMoving.addMouseListener(new MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent me) {
            x = me.getX();
            y = me.getY();
        }
    });
    panelMoving.addMouseMotionListener(new MouseAdapter() {
        @Override
        public void mouseDragged(MouseEvent me) {
            frame.setLocation(me.getXOnScreen() - x, me.getYOnScreen() - y);
        }
    });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMoving = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        listMenu1 = new poly.edu.swing.ListMenu<>();

        setPreferredSize(new java.awt.Dimension(215, 620));

        panelMoving.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/edu/icons/Color wheel.png"))); // NOI18N
        jLabel1.setText("SHOP GIÀY THỂ THAO");

        javax.swing.GroupLayout panelMovingLayout = new javax.swing.GroupLayout(panelMoving);
        panelMoving.setLayout(panelMovingLayout);
        panelMovingLayout.setHorizontalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMovingLayout.setVerticalGroup(
            panelMovingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMovingLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMoving, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMoving, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(listMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private poly.edu.swing.ListMenu<String> listMenu1;
    private javax.swing.JPanel panelMoving;
    // End of variables declaration//GEN-END:variables
}
