/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ViewFrame;

import Model.Users2;
import Repository.KhuyenMai2Repository;
import entity.ComboItem;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FPTSHOP
 */
public class KhuyenMai extends javax.swing.JPanel {

        ArrayList<Users2> km;
    private DefaultTableModel dtm;
    KhuyenMai2Repository khuyenMaiRepository= new KhuyenMai2Repository();
    // Định dạng ngày
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    public KhuyenMai() throws SQLException {
        initComponents();
           dtm = (DefaultTableModel) tblKM.getModel();
        km = khuyenMaiRepository.getAll();


        showDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        txtTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateKT = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdPhanTram = new javax.swing.JRadioButton();
        rdVND = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        dateBD = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        txtGiaTriGiam = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbbTrangThai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKM = new javax.swing.JTable();

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel2.setText("Tên Khuyến Mại");

        dateKT.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Ngày Kết Thúc");

        jLabel7.setText("Hình thức giảm");

        buttonGroup1.add(rdPhanTram);
        rdPhanTram.setText("%");

        buttonGroup1.add(rdVND);
        rdVND.setText("VND");

        jLabel3.setText("Ngày Bắt Đầu");

        dateBD.setDateFormatString("yyyy-MM-dd");

        jLabel5.setText("Giá Trị Giảm");

        jLabel8.setText("Trạng Thái");

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        cbbTrangThai.setToolTipText("");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnUpdate.setText("Cập Nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên KM", "Ngày BD", "Ngày KT", "Giá trị giảm", "Hình thức", "Trạng thái"
            }
        ));
        tblKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(rdVND)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rdPhanTram))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(24, 24, 24)))
                                    .addComponent(jLabel4)
                                    .addComponent(dateKT, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbbTrangThai, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtGiaTriGiam, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dateBD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(jLabel8))))))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(btnReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnThem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateKT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGiaTriGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdPhanTram)
                            .addComponent(rdVND)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        search();
        // ViewKhuyenMai.java

        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Add();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clean();
        showDataTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKMMouseClicked
        // TODO add your handling code here:
        int index = tblKM.getSelectedRow();
        this.ToConTro(index);
    }//GEN-LAST:event_tblKMMouseClicked

 private void showDataTable() {
      dtm.setRowCount(0); // Xóa dữ liệu hiện tại trên bảng

    for (Users2 km : km) {
        // Xác định trạng thái
        String trangThai;
        if (km.getTrangthai() == 0) {
            trangThai = "Đang hoạt động";
        } else {
            trangThai = "Ngừng hoạt động";
        }

        // Tạo hàng dữ liệu cho bảng
        Object[] row = {
            km.getID(),
            km.getTenKM(),
            km.getNgayBatDau(),
            km.getNgayKetThuc(),
            km.getGiaTriGiam(),
            km.getHinhThucKM(),
            trangThai // Thay thế trạng thái với giá trị đúng
        };
        
        // Thêm hàng vào bảng
        dtm.addRow(row);
    }
    }
     
     private void ToConTro(int index) {

        // Giả sử index là chỉ số bạn muốn truy cập
        // An toàn để sử dụng nv
        Users2 kvm = km.get(index);
        txtTen.setText(kvm.getTenKM());
 
        if (kvm.getNgayBatDau() != null) {
            dateBD.setDate(kvm.getNgayBatDau());
        } else {
            dateBD.setDate(null); // Đặt ngày là null nếu không có giá trị
        }
        
        if (kvm.getNgayKetThuc() != null) {
            dateKT.setDate(kvm.getNgayKetThuc());
        } else {
            dateKT.setDate(null); // Đặt ngày là null nếu không có giá trị
        }
        
        txtGiaTriGiam.setText(Double.toString(kvm.getGiaTriGiam()));
        
        
        String hinhThucKM = kvm.getHinhThucKM();
    if ("VND".equals(hinhThucKM)) {
        rdVND.setSelected(true);
        rdPhanTram.setSelected(false);
    } else if ("%".equals(hinhThucKM)) {
        rdVND.setSelected(false);
        rdPhanTram.setSelected(true);
    } else {
        rdVND.setSelected(false);
        rdPhanTram.setSelected(false);
    }
        
        Object trangThai = kvm.getTrangthai();
        if (trangThai != null) {
            cbbTrangThai.setSelectedItem(trangThai.toString());
        } else {
            cbbTrangThai.setSelectedIndex(-1); // Nếu không có giá trị hợp lệ, đặt lựa chọn thành không
        }
        
        km.add(kvm);
    }
     
     
     
     private void Add() {
    Users2 km = new Users2();

    try {
        // Kiểm tra tên khuyến mãi
        String tenKM = txtTen.getText().trim();
        if (tenKM.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên khuyến mãi không được để trống.");
            return;
        }
        km.setTenKM(tenKM);

        // Kiểm tra ngày bắt đầu
        Date ngayBD = dateBD.getDate();
        if (ngayBD == null) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu không hợp lệ.");
            return;
        }
        
        // Kiểm tra ngày kết thúc
        Date ngayKT = dateKT.getDate();
        if (ngayKT == null) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc không hợp lệ.");
            return;
        }
        
        // Kiểm tra ngày bắt đầu phải trước ngày kết thúc
        if (ngayBD.after(ngayKT)) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải trước ngày kết thúc.");
            return;
        }

        km.setNgayBatDau(ngayBD);
        km.setNgayKetThuc(ngayKT);

        // Kiểm tra hình thức khuyến mãi
        String hinhThucKM;
        if (rdVND.isSelected()) {
            hinhThucKM = "VND"; // Hoặc giá trị String nào bạn chọn để đại diện cho VND
        } else if (rdPhanTram.isSelected()) {
            hinhThucKM = "%"; // Hoặc giá trị String nào đó đại diện cho tỷ lệ phần trăm
        } else {
            JOptionPane.showMessageDialog(this, "Chọn hình thức khuyến mãi.");
            return;
        }
        km.setHinhThucKM(hinhThucKM);

        // Kiểm tra giá trị giảm
        String giaTriGiamStr = txtGiaTriGiam.getText().trim();
        if (giaTriGiamStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giá trị giảm không được để trống.");
            return;
        }

        Double giaTriGiam;
        try {
            giaTriGiam = Double.parseDouble(giaTriGiamStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá trị giảm không hợp lệ. Vui lòng nhập số hợp lệ.");
            return;
        }
        km.setGiaTriGiam(giaTriGiam);

        // Kiểm tra trạng thái
        if (cbbTrangThai.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Trạng thái không được để trống.");
            return;
        }
        km.setTrangthai(Integer.parseInt(cbbTrangThai.getSelectedItem().toString()));

        // Thực hiện thêm dữ liệu vào cơ sở dữ liệu
        khuyenMaiRepository.addKM(km);
        JOptionPane.showMessageDialog(this, "Thêm thành công!");
        this.km = khuyenMaiRepository.getAll();
        showDataTable();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Có lỗi khi thêm dữ liệu.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu.");
    } catch (Exception e) {
        e.printStackTrace();
    }
}



    private LocalDate getCurrentLocalDateWithoutTime() {
        LocalDateTime now = LocalDateTime.now();
        return now.toLocalDate();
    }
    
    
    
    private void update() {
        int index = tblKM.getSelectedRow();
        Users2 nvus = km.get(index);

        nvus.setTenKM(txtTen.getText());
        Date ngayBD = dateBD.getDate();
        if (ngayBD != null) {
            nvus.setNgayBatDau(new java.sql.Date(ngayBD.getTime())); // Đảm bảo ngày  là java.sql.Date
        }
        Date ngayKT = dateKT.getDate();
        if (ngayKT != null) {
            nvus.setNgayKetThuc(new java.sql.Date(ngayKT.getTime())); // Đảm bảo ngày  là java.sql.Date
        }
        String hinhThucKM = null;
    if (rdVND.isSelected()) {
        hinhThucKM = "VND";
    } else if (rdPhanTram.isSelected()) {
        hinhThucKM = "%";
    }
    if (hinhThucKM == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn hình thức khuyến mãi.");
        return;
    }
    nvus.setHinhThucKM(hinhThucKM);
    
        // Cập nhật giá trị giảm
    String giaTriGiamStr = txtGiaTriGiam.getText().trim();
    if (giaTriGiamStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Giá trị giảm không được để trống.");
        return;
    }
    Double giaTriGiam;
    try {
        giaTriGiam = Double.parseDouble(giaTriGiamStr);
        if (giaTriGiam < 0) { // Kiểm tra giá trị giảm không âm
            JOptionPane.showMessageDialog(this, "Giá trị giảm không được là số âm.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá trị giảm không hợp lệ. Vui lòng nhập số hợp lệ.");
        return;
    }
    nvus.setGiaTriGiam(giaTriGiam);
        if (cbbTrangThai.getSelectedItem() != null) {
            nvus.setTrangthai(Integer.parseInt(cbbTrangThai.getSelectedItem().toString())); // Đảm bảo TT là int
        }

        
        try {
            khuyenMaiRepository.update(nvus);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            this.km = khuyenMaiRepository.getAll();
            showDataTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    private void search(){
        String idStr = txtTimKiem.getText().trim();
    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập ID khuyến mãi.");
        return;
    }
    
    try {
        int id = Integer.parseInt(idStr);
        // Giả sử khuyenMaiRepository là một đối tượng quản lý cơ sở dữ liệu của bạn
        Users2 km = khuyenMaiRepository.getKhuyenMaiById(id);
        
        if (km != null) {
            // Cập nhật bảng với dữ liệu tìm được
            dtm.setRowCount(0); // Xóa dữ liệu cũ
            Object[] row = {
                km.getID(),
                km.getTenKM(),
                km.getNgayBatDau(),
                km.getNgayKetThuc(),
                km.getGiaTriGiam(),
                km.getHinhThucKM(),
                km.getTrangthai()
            };
            dtm.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy khuyến mãi với ID này.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID không hợp lệ. Vui lòng nhập số.");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Lỗi cơ sở dữ liệu: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi không xác định: " + e.getMessage());
    }
        
    }

     
     
     
     
     private void clean() {
        txtTen.setText("");
        dateBD.setDate(null);
        dateKT.setDate(null);
        txtGiaTriGiam.setText("");
        rdVND.setSelected(true);
        cbbTrangThai.setSelectedIndex(0);
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private com.toedter.calendar.JDateChooser dateBD;
    private com.toedter.calendar.JDateChooser dateKT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdPhanTram;
    private javax.swing.JRadioButton rdVND;
    private javax.swing.JTable tblKM;
    private javax.swing.JTextField txtGiaTriGiam;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
